screen = <empty> <empty> [SHADOWS] [CAMERA]
screen.SHADOWS = <empty> <empty> shadowMapResolution
screen.CAMERA = <empty> <empty> BLOOM BLOOM_STRENGTH EXPOSURE

sliders = shadowMapResolution BLOOM_STRENGTH EXPOSURE