colortex4.format=RGBA16
colortex4.clear=true

clouds=off

screen = <empty> <empty> [SHADOWS] [CAMERA]
screen.SHADOWS = <empty> <empty> shadowMapResolution
screen.CAMERA = <empty> <empty> BLOOM BLOOM_STRENGTH EXPOSURE SATURATION

sliders = shadowMapResolution BLOOM_STRENGTH EXPOSURE SATURATION